apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-upload
  namespace: blog
  labels:
    {{- include "blog.workloadLabels" . | nindent 4 }}
    {{- include "blog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.upload.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: blog
  labels:
    {{- include "blog.workloadLabels" . | nindent 4 }}
    {{- include "blog.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.application.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: application
  template:
    metadata:
      labels:
        {{- include "blog.workloadLabels" . | nindent 8 }}
    spec:
      {{- include "blog.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: application
          image: {{ include "blog.image" . }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
          {{- include "blog.envFrom" . | nindent 10 }}
          env:
            - name: PORT
              value: "{{ .Values.application.port }}"
            - name: UPLOAD_PATH
              value: {{ .Values.persistence.upload.mountPath | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: upload
              mountPath: {{ .Values.persistence.upload.mountPath }}
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: application-upload
---
apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: blog
  labels:
    {{- include "blog.workloadLabels" . | nindent 4 }}
    {{- include "blog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: application
  ports:
    - name: http
      port: {{ .Values.application.port }}
      targetPort: http
